[package]
name = "farm.study-api"
version = "0.1.0"
authors = ["Pocket of Weird <hartzlernathan@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = { version = "0.4.0", default-features = false, features = ["cypher_pool", "json"] }
rusted_cypher = "1.1.0"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.91"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
http = "0.1.17"
