[package]
name = "api"
version = "0.1.0"
authors = ["Pocket of Weird <hartzlernathan@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rusted_cypher = "1.1.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["cypher_pool"]
